version: '3'

tasks:
  run:
    cmds:
       - source .env && go run cmd/auth/main.go cmd/auth/app.go
    desc: "Load .env file and run Go application"

  build:
    cmds:
       - go build -o bin/auth cmd/auth/main.go cmd/auth/app.go
    desc: "Build Go application"